locations:
  - &fooLocation !!models.event.Location
    id: 1
    title: Президент готель
    address: Київ, вул. Госпітальна, 12

  - &barLocation !!models.event.Location
    id: 2
    title: Український католицький університет
    address: Львів, вул. Хуторівка, 35a

stages:
  - &firstStage !!models.event.Stage
    title: First stage
    capacity: 33

  - &secondStage !!models.event.Stage
    title: Second stage
    capacity: 44

  - &thirdStage !!models.event.Stage
    title: Third stage stage
    capacity: 55

  - &fourthStage !!models.event.Stage
    title: Fourth stage
    capacity: 66

linkedAccounts:
  - &fooAccount !!models.authentication.LinkedAccount
    id: 1
    providerUserId: $2a$10$NN5qwKjNCHVARgDaaLZiOupVG228iPundphAV8zAgWiWYoSaSV/uy
    providerKey: password

speeches:
  - &firstSpeech !!models.event.Speech
    title: First Speech
    speakers:

  - &secondSpeech !!models.event.Speech
    title: Second Speech
    speakers:

slots:
  - &firstSlot !!models.event.slot.SpeechSlot
    start: !!timestamp 2013-09-02 09:00:00 +3
    end: !!timestamp 2013-09-02 18:00:00 +3
    stage:
      *firstStage
    speech:
      *firstSpeech

  - &secondSlot !!models.event.slot.SpeechSlot
    start: !!timestamp 2013-09-03 09:00:00 +3
    end: !!timestamp 2013-09-03 18:00:00 +3
    stage:
      *secondStage
    speech:
      *secondSpeech

events:
  - &event1 !!models.event.Event
    title: XP Days 2014
    description: event1 - n/a
    location: *fooLocation
    stages:
      - *firstStage
      - *secondStage
      - *thirdStage
      - *fourthStage
    slots:
      - *firstSlot
      - *secondSlot

  - &event2 !!models.event.Event
    title: XP Days 2013
    description: event2 - n/a
    location: *barLocation

  - &event3 !!models.event.Event
    title: XP Days 2012
    description: event3 - n/a
    location: *barLocation

  - &event4 !!models.event.Event
    title: XP Days 2011
    description: event4 - n/a
    location: *barLocation

  - &event5 !!models.event.Event
    title: XP Days 2010
    description: event5 - n/a
    location: *barLocation

  - &event6 !!models.event.Event
    title: XP Days 2009
    description: event6 - n/a
    location: *barLocation

  - &event7 !!models.event.Event
    title: XP Days 2008
    description: event7 - n/a
    location: *barLocation

  - &event8 !!models.event.Event
    title: XP Days 2007
    description: event8 - n/a
    location: *barLocation

  - &event9 !!models.event.Event
    title: XP Days 2006
    description: event9 - n/a
    location: *barLocation

  - &event10 !!models.event.Event
    title: XP Days 2005
    description: event10 - n/a
    location: *barLocation


  - &event11 !!models.event.Event
    title: XP Days 2004
    description: event11 - n/a
    location: *fooLocation

  - &event12 !!models.event.Event
    title: XP Days 2003
    description: event12 - n/a
    location: *barLocation

  - &event13 !!models.event.Event
    title: XP Days 2002
    description: event13 - n/a
    location: *barLocation

  - &event14 !!models.event.Event
    title: XP Days 2001
    description: event14 - n/a
    location: *barLocation

  - &event15 !!models.event.Event
    title: XP Days 2000
    description: event15 - n/a
    location: *barLocation

  - &event16 !!models.event.Event
    title: XP Days 1999
    description: event16 - n/a
    location: *barLocation

  - &event17 !!models.event.Event
    title: XP Days 1998
    description: event17 - n/a
    location: *barLocation

  - &event18 !!models.event.Event
    title: XP Days 1997
    description: event18 - n/a
    location: *barLocation

  - &event19 !!models.event.Event
    title: XP Days 1996
    description: event19 - n/a
    location: *barLocation

  - &event20 !!models.event.Event
    title: XP Days 1995
    description: event20 - n/a
    location: *barLocation

  - &event21 !!models.event.Event
    title: XP Days 1994
    description: event21 - n/a
    location: *fooLocation

  - &event22 !!models.event.Event
    title: XP Days 1993
    description: event22 - n/a
    location: *barLocation

  - &event23 !!models.event.Event
    title: XP Days 1992
    description: event23 - n/a
    location: *barLocation

  - &event24 !!models.event.Event
    title: XP Days 1991
    description: event24 - n/a
    location: *barLocation

  - &event25 !!models.event.Event
    title: XP Days 1990
    description: event25 - n/a
    location: *barLocation

  - &event26 !!models.event.Event
    title: XP Days 1989
    description: event26 - n/a
    location: *barLocation

  - &event27 !!models.event.Event
    title: XP Days 1988
    description: event27 - n/a
    location: *barLocation

  - &event28 !!models.event.Event
    title: XP Days 1987
    description: event28 - n/a
    location: *barLocation

  - &event29 !!models.event.Event
    title: XP Days 1986
    description: event29 - n/a
    location: *barLocation

  - &event30 !!models.event.Event
    title: XP Days 1985
    description: event30 - n/a
    location: *barLocation

users:
- !!models.authentication.User
  id: 1
  email: foo@bar.com
  name: Alex
  firstName: null
  lastName: null
  lastLogin: null
  active: true
  emailValidated: true
  roles:
    - !!models.authentication.SecurityRole
      id: 1
  linkedAccounts:
    - *fooAccount
  permissions:
  events:
    - *event1
    - *event2
    - *event3
    - *event4
    - *event5
    - *event6
    - *event7
    - *event8
    - *event9
    - *event10
    - *event11
    - *event12
    - *event13
    - *event14
    - *event15
    - *event16
    - *event17
    - *event18
    - *event19
    - *event20
    - *event21
    - *event22
    - *event23
    - *event24
    - *event25
    - *event26
    - *event27
    - *event28
    - *event29
    - *event30

