locations:
  - &fooLocation !!models.event.Location
    title: Президент готель
    address: Київ, вул. Госпітальна, 12

  - &barLocation !!models.event.Location
    title: Український католицький університет
    address: Львів, вул. Хуторівка, 35a

stages:
  - &stage1 !!models.event.Stage
    title: North
    capacity: 100

  - &stage2 !!models.event.Stage
    title: South
    capacity: 200

  - &stage3 !!models.event.Stage
    title: West
    capacity: 300

  - &stage4 !!models.event.Stage
    title: East
    capacity: 400

speakers:
  - &speaker1 !!models.event.Speaker
    name: Johnie Walker
    position: enterpreneur
    description: Owns alchohol business
    speeches:

  - &speaker2 !!models.event.Speaker
    name: John Smith
    position: Movie Star
    description: Brigth
    speeches:

  - &speaker3 !!models.event.Speaker
    name: Schon Connery
    position: Artist
    description: GR
    speeches:

speeches:
  - &speech1 !!models.event.Speech
    title: Speech 1
    speakers:
      - *speaker1
      - *speaker2
      - *speaker3

  - &speech2 !!models.event.Speech
    title: Speech 2
    speakers:
      - *speaker1
      - *speaker2

  - &speech3 !!models.event.Speech
    title: Speech 3
    speakers:
      - *speaker1

slots:
  - &slot1 !!models.event.slot.SpeechSlot
    start: !!timestamp 2013-09-02 09:00:00 +3
    end: !!timestamp 2013-09-02 10:00:00 +3
    stage:
      *stage1
    speech:
      *speech1

  - &slot2 !!models.event.slot.OrganizationalSlot
    title: Org Slot
    start: !!timestamp 2013-09-02 11:00:00 +3
    end: !!timestamp 2013-09-02 12:45:00 +3

  - &slot3 !!models.event.slot.OrganizationalSlot
    title: First Ring
    start: !!timestamp 2013-09-01 09:00:00 +3
    end: !!timestamp 2013-09-01 10:00:00 +3

  - &slot4 !!models.event.slot.SpeechSlot
    start: !!timestamp 2013-09-01 10:00:00 +3
    end: !!timestamp 2013-09-01 11:00:00 +3
    stage:
      *stage2
    speech:
      *speech2

  - &slot5 !!models.event.slot.OrganizationalSlot
    title: Preparation, inventory
    start: !!timestamp 2013-09-01 08:00:00 +3
    end: !!timestamp 2013-09-01 09:00:00 +3

  - &slot6 !!models.event.slot.SpeechSlot
    start: !!timestamp 2013-09-01 10:00:00 +3
    end: !!timestamp 2013-09-01 11:00:00 +3
    stage:
      *stage1
    speech:
      *speech1

linkedAccounts:
  - &fooAccount !!models.authentication.LinkedAccount
    id: 1
    providerUserId: $2a$10$NN5qwKjNCHVARgDaaLZiOupVG228iPundphAV8zAgWiWYoSaSV/uy
    providerKey: password

events:
  - &event1 !!models.event.Event
    title: XP Days 2014
    description: event1 - n/a
    location: *fooLocation
    stages:
      - *stage1
      - *stage2
    slots:
      - *slot1
      - *slot2
      - *slot3
      - *slot4
      - *slot5
      - *slot6
    speeches:
      - *speech1
      - *speech2
      - *speech3
    speakers:
      - *speaker1
      - *speaker2
      - *speaker3

  - &event2 !!models.event.Event
    title: XP Days 2013
    description: event2 - n/a
    location: *barLocation
    stages:
      - *stage3
      - *stage4

  - &event3 !!models.event.Event
    title: XP Days 2012
    description: event3 - n/a

  - &event4 !!models.event.Event
    title: XP Days 2011
    description: event4 - n/a

  - &event5 !!models.event.Event
    title: XP Days 2010
    description: event5 - n/a

  - &event6 !!models.event.Event
    title: XP Days 2009
    description: event6 - n/a

  - &event7 !!models.event.Event
    title: XP Days 2008
    description: event7 - n/a

  - &event8 !!models.event.Event
    title: XP Days 2007
    description: event8 - n/a

  - &event9 !!models.event.Event
    title: XP Days 2006
    description: event9 - n/a

  - &event10 !!models.event.Event
    title: XP Days 2005
    description: event10 - n/a

  - &event11 !!models.event.Event
    title: XP Days 2004
    description: event11 - n/a

  - &event12 !!models.event.Event
    title: XP Days 2003
    description: event12 - n/a

  - &event13 !!models.event.Event
    title: XP Days 2002
    description: event13 - n/a

  - &event14 !!models.event.Event
    title: XP Days 2001
    description: event14 - n/a

  - &event15 !!models.event.Event
    title: XP Days 2000
    description: event15 - n/a

  - &event16 !!models.event.Event
    title: XP Days 1999
    description: event16 - n/a

  - &event17 !!models.event.Event
    title: XP Days 1998
    description: event17 - n/a

  - &event18 !!models.event.Event
    title: XP Days 1997
    description: event18 - n/a

  - &event19 !!models.event.Event
    title: XP Days 1996
    description: event19 - n/a

  - &event20 !!models.event.Event
    title: XP Days 1995
    description: event20 - n/a

  - &event21 !!models.event.Event
    title: XP Days 1994
    description: event21 - n/a

  - &event22 !!models.event.Event
    title: XP Days 1993
    description: event22 - n/a

  - &event23 !!models.event.Event
    title: XP Days 1992
    description: event23 - n/a

  - &event24 !!models.event.Event
    title: XP Days 1991
    description: event24 - n/a

  - &event25 !!models.event.Event
    title: XP Days 1990
    description: event25 - n/a

  - &event26 !!models.event.Event
    title: XP Days 1989
    description: event26 - n/a

  - &event27 !!models.event.Event
    title: XP Days 1988
    description: event27 - n/a

  - &event28 !!models.event.Event
    title: XP Days 1987
    description: event28 - n/a

  - &event29 !!models.event.Event
    title: XP Days 1986
    description: event29 - n/a

  - &event30 !!models.event.Event
    title: XP Days 1985
    description: event30 - n/a

users:
- !!models.authentication.User
  id: 1
  email: foo@bar.com
  name: Alex
  firstName: null
  lastName: null
  lastLogin: null
  active: true
  emailValidated: true
  roles:
    - !!models.authentication.SecurityRole
      id: 1
  linkedAccounts:
    - *fooAccount
  permissions:
  events:
    - *event1
    - *event2
    - *event3
    - *event4
    - *event5
    - *event6
    - *event7
    - *event8
    - *event9
    - *event10
    - *event11
    - *event12
    - *event13
    - *event14
    - *event15
    - *event16
    - *event17
    - *event18
    - *event19
    - *event20
    - *event21
    - *event22
    - *event23
    - *event24
    - *event25
    - *event26
    - *event27
    - *event28
    - *event29
    - *event30

